description: Den reklamfria sajten med vaggvisor
google_analytics: UA-64961-15
lang: sv
permalink: /:title/
plugins:
  - jekyll-sitemap
show_downloads: false
title: Kända vaggvisor
url: https://vaggvisor.org
collections:
  my_categories:
    output: true
    permalink: /category/:slug/

defaults:
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: by_category
  -
    scope:
      path: ""
      type: posts
    values:
      layout: lyrics
