description: Den reklamfria sajten med vaggvisor
google_analytics: UA-64961-15
lang: sv
permalink: /:title/
show_downloads: false
title: Kända vaggvisor
url: https://vaggvisor.org
collections:
  authors:
    output: true
    permalink: /category/:slug/

defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
  -
    scope:
      path: ""
      type: posts
    values:
      layout: lyrics
